---
# ============================================
# Buzz BD Agent v5.3.2 — Akash SDL
# OpenClaw v2026.2.19 + ClawRouter v0.9.39
# BlockRun x402 — No API keys, USDC payments
# github.com/buzzbysolcex/buzz-bd-agent
# ============================================

version: "2.0"

services:
  buzz-bd:
    image: ghcr.io/buzzbysolcex/buzz-bd-agent:v5.3.2
    expose:
      - port: 18789
        as: 18789
        to:
          - global: true
    env:
      - OPENCLAW_STATE_DIR=/data/.openclaw
      - OPENCLAW_WORKSPACE_DIR=/data/workspace
      - NPM_CONFIG_PREFIX=/data/.npm-global
      - TELEGRAM_BOT_TOKEN=<SET_ON_DEPLOY>
      - MINIMAX_API_KEY=<SET_ON_DEPLOY>
      - BLOCKRUN_WALLET_KEY=<SET_ON_DEPLOY>
    params:
      storage:
        data:
          mount: /data
          size: 10Gi
          readOnly: false

profiles:
  compute:
    buzz-bd:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      pricing:
        buzz-bd:
          denom: uakt
          amount: 10000

deployment:
  buzz-bd:
    akash:
      profile: buzz-bd
      count: 1
