---
# ============================================
# Buzz BD Agent — ROLLBACK SDL
# OpenClaw v2026.2.2 (current stable on Akash)
# USE ONLY IF v2026.2.19 DEPLOYMENT FAILS
# ============================================

version: "2.0"

services:
  buzz-bd:
    image: openclaw/openclaw:v2026.2.2
    expose:
      - port: 18789
        as: 18789
        to:
          - global: true
    env:
      - OPENCLAW_STATE_DIR=/data/.openclaw
      - OPENCLAW_WORKSPACE_DIR=/data/workspace
      - NPM_CONFIG_PREFIX=/data/.npm-global
      - ANTHROPIC_API_KEY=<SET_ON_DEPLOY>
      - OPENROUTER_API_KEY=<SET_ON_DEPLOY>
    params:
      storage:
        data:
          mount: /data
          size: 10Gi
          readOnly: false

profiles:
  compute:
    buzz-bd:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          - name: data
            size: 10Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    akash:
      pricing:
        buzz-bd:
          denom: uakt
          amount: 10000

deployment:
  buzz-bd:
    akash:
      profile: buzz-bd
      count: 1
