#!/bin/bash

export OPENCLAW_STATE_DIR=/data/.openclaw
export OPENCLAW_WORKSPACE_DIR=/data/workspace
export NPM_CONFIG_PREFIX=/data/.npm-global
export PATH="/data/.npm-global/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"

echo "============================================"
echo "  Buzz BD Agent v6.0.3 — Hummingbot Edition"
echo "  OpenClaw v2026.2.24 + Bankr + ATV + HBot"
echo "  5-Service Stack on Akash Network"
echo "  State:     $OPENCLAW_STATE_DIR"
echo "  Workspace: $OPENCLAW_WORKSPACE_DIR"
echo "  Persistent: /data (10Gi)"
echo "============================================"

# ========== CREATE DIRECTORIES ==========
mkdir -p /data/.openclaw \
         /data/workspace \
         /data/workspace/skills \
         /data/workspace/memory \
         /data/.npm-global \
         /data/bankr \
         /data/bankr/deploys \
         /data/pipeline \
         /data/outreach \
         /data/outreach/drafts \
         /data/logs \
         /data/atv \
         /data/hummingbot \
         /data/hummingbot/trade-history

# ========== SYNC SKILLS FROM IMAGE ==========
if [ -d "/opt/buzz-skills" ]; then
  cp -r /opt/buzz-skills/* /data/workspace/skills/ 2>/dev/null || true
  echo "[entrypoint] Skills synced from image"
fi

# ========== GENERATE BANKR CONFIG (PERSISTENT) ==========
BANKR_CONFIG="/data/bankr/bankr-config.json"
if [ ! -f "$BANKR_CONFIG" ]; then
  echo "[entrypoint] Creating Bankr config..."
  cat > "$BANKR_CONFIG" << BANKREOF
{
  "endpoint": "${BANKR_API_ENDPOINT:-https://api.bankr.bot/token-launches/deploy}",
  "partnerKey": "${BANKR_API_KEY}",
  "feeWallet": "${BANKR_FEE_WALLET:-0x2Dc03124091104E7798C0273D96FC5ED65F05aA9}",
  "deployWallet": "${BANKR_DEPLOY_WALLET:-0xfa04c7d627ba707a1ad17e72e094b45150665593}",
  "chain": "${BANKR_CHAIN:-base}",
  "feeDistribution": {
    "creator": 7505,
    "bankr": 1805,
    "protocol": 500,
    "alt": 190
  },
  "commands": {
    "launch": "/launch [name] [symbol] [description] --wallet OPTIONAL_CLIENT_WALLET",
    "deploys": "/deploys - list all deployed tokens",
    "deploy_stats": "/deploy_stats - show volume and fees"
  },
  "deploys": []
}
BANKREOF
  echo "[entrypoint] Bankr config created at $BANKR_CONFIG"
else
  echo "[entrypoint] Bankr config exists (persistent), skipping"
fi

# ========== GENERATE ATV CONFIG (NEW in v6.0.3) ==========
ATV_CONFIG="/data/atv/atv-config.json"
if [ ! -f "$ATV_CONFIG" ]; then
  echo "[entrypoint] Creating ATV identity config..."
  cat > "$ATV_CONFIG" << ATVEOF
{
  "endpoint": "${ATV_API_URL:-https://api.web3identity.com/api/ens/batch-resolve}",
  "include": "name,twitter,github",
  "dailyLimit": ${ATV_DAILY_LIMIT:-100},
  "cacheTtlMinutes": ${ATV_CACHE_TTL_MINUTES:-15},
  "enabled": ${ATV_ENABLED:-true},
  "scoring": {
    "IDENTITY_VERIFIED": 5,
    "ENS_HOLDER": 3,
    "ANON_DEPLOYER": -3
  },
  "triggers": {
    "ethBaseScoreThreshold": 70,
    "crossChainEnabled": true,
    "firecrawlTeamAddresses": true
  },
  "pauseThreshold": 80,
  "stats": {
    "totalCalls": 0,
    "cacheHits": 0,
    "lastResetDate": null
  }
}
ATVEOF
  echo "[entrypoint] ATV config created at $ATV_CONFIG"
else
  echo "[entrypoint] ATV config exists (persistent), skipping"
fi

# ========== GENERATE HUMMINGBOT CONNECTION CONFIG (NEW in v6.0.3) ==========
HBOT_CONFIG="/data/hummingbot/hbot-connection.json"
echo "[entrypoint] Writing Hummingbot connection config..."
cat > "$HBOT_CONFIG" << HBOTEOF
{
  "apiUrl": "${HUMMINGBOT_API_URL:-http://hummingbot-api:8000}",
  "username": "${HUMMINGBOT_API_USERNAME:-buzzmm}",
  "password": "${HUMMINGBOT_API_PASSWORD:-BuzzMM2026!SolCex}",
  "enabled": ${HUMMINGBOT_ENABLED:-true},
  "autoStopLossPercent": 5,
  "maxConcurrentBots": 5,
  "strategies": {
    "postListing": "pure_market_making",
    "initialLiquidity": "concentrated_lp",
    "accumulation": "dca"
  },
  "commands": {
    "mm_start": "/mm_start TOKEN PAIR EXCHANGE — Start market making bot",
    "mm_stop": "/mm_stop BOT_ID — Stop a running bot",
    "mm_status": "/mm_status — Show all active MM bots with PnL",
    "mm_pnl": "/mm_pnl — Detailed PnL breakdown",
    "mm_balance": "/mm_balance — Portfolio balances across exchanges",
    "mm_orderbook": "/mm_orderbook TOKEN PAIR — Current orderbook depth"
  }
}
HBOTEOF
echo "[entrypoint] Hummingbot config created at $HBOT_CONFIG"

# ========== GENERATE ENV FILE FOR CRON PASSTHROUGH ==========
ENV_FILE="/data/workspace/.env"
echo "[entrypoint] Writing .env for cron sub-agent passthrough..."
cat > "$ENV_FILE" << ENVEOF
# Auto-generated by entrypoint.sh v6.0.3 — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Cron sub-agents source this file to access API keys

# LLM
MINIMAX_API_KEY=${MINIMAX_API_KEY}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

# Bankr Partner API
BANKR_API_KEY=${BANKR_API_KEY}
BANKR_API_ENDPOINT=${BANKR_API_ENDPOINT}
BANKR_FEE_WALLET=${BANKR_FEE_WALLET}
BANKR_DEPLOY_WALLET=${BANKR_DEPLOY_WALLET}
BANKR_CHAIN=${BANKR_CHAIN}

# ATV Web3 Identity (NEW in v6.0.3)
ATV_API_URL=${ATV_API_URL}
ATV_DAILY_LIMIT=${ATV_DAILY_LIMIT:-100}
ATV_CACHE_TTL_MINUTES=${ATV_CACHE_TTL_MINUTES:-15}
ATV_ENABLED=${ATV_ENABLED:-true}

# Hummingbot (NEW in v6.0.3)
HUMMINGBOT_API_URL=${HUMMINGBOT_API_URL}
HUMMINGBOT_API_USERNAME=${HUMMINGBOT_API_USERNAME}
HUMMINGBOT_API_PASSWORD=${HUMMINGBOT_API_PASSWORD}
HUMMINGBOT_ENABLED=${HUMMINGBOT_ENABLED:-true}

# Intelligence APIs
GROK_API_KEY=${GROK_API_KEY}
SERPER_API_KEY=${SERPER_API_KEY}
ALLIUM_API_KEY=${ALLIUM_API_KEY}
FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
HYPERBROWSER_API_KEY=${HYPERBROWSER_API_KEY}
HELIUS_API_KEY=${HELIUS_API_KEY}

# DexScreener (free, no key)
DEXSCREENER_BASE_URL=${DEXSCREENER_BASE_URL:-https://api.dexscreener.com}

# Gmail
GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
GMAIL_ADDRESS=${GMAIL_ADDRESS}

# Moltbook
MOLTBOOK_AGENT_ID=${MOLTBOOK_AGENT_ID}
MOLTBOOK_API_KEY=${MOLTBOOK_API_KEY}

# Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

# Feature Flags
PERPLEXITY_ENABLED=${PERPLEXITY_ENABLED:-false}
DEFAULT_MODEL=${DEFAULT_MODEL:-minimax/MiniMax-M2.5}
ENVEOF
echo "[entrypoint] .env written at $ENV_FILE"

# ========== GENERATE OPENCLAW CONFIG ==========
CONFIG="/data/.openclaw/openclaw.json"
echo "[entrypoint] Generating OpenClaw config from env vars..."
cat > "$CONFIG" << JSONEOF
{
  "gateway": { "port": 18789, "mode": "local" },
  "channels": { "telegram": { "enabled": true, "botToken": "$TELEGRAM_BOT_TOKEN" } },
  "env": {
    "MINIMAX_API_KEY": "$MINIMAX_API_KEY",
    "OPENROUTER_API_KEY": "$OPENROUTER_API_KEY"
  },
  "models": {
    "providers": {
      "akashml": {
        "baseUrl": "https://api.akashml.com/v1",
        "apiKey": "akml-VLgEXJDTuTPueuoGPXVtoPGzUfarBCNL",
        "api": "openai-completions",
        "models": [{
          "id": "Qwen/Qwen3-30B-A3B", "name": "Qwen3 30B",
          "contextWindow": 128000, "maxTokens": 8192
        }]
      }
    }
  },
  "agents": {
    "defaults": {
      "models": {
        "minimax/MiniMax-M2.5": {"alias": "MiniMax"},
        "openrouter/meta-llama/llama-3.3-70b-instruct:free": {"alias": "Llama70B"},
        "akashml/Qwen/Qwen3-30B-A3B": {"alias": "Qwen30B"}
      },
      "model": {
        "primary": "${DEFAULT_MODEL:-minimax/MiniMax-M2.5}",
        "fallbacks": [
          "openrouter/meta-llama/llama-3.3-70b-instruct:free",
          "akashml/Qwen/Qwen3-30B-A3B"
        ]
      },
      "subagents": { "maxConcurrent": 8 }
    }
  }
}
JSONEOF
echo "[entrypoint] OpenClaw config generated at $CONFIG"

# ========== BOOT SELF-CHECK ==========
echo ""
echo "========== BOOT SELF-CHECK v6.0.3 =========="

# Cron schedule
if [ -f "/data/workspace/memory/cron-schedule.json" ]; then
  CRON_COUNT=$(cat /data/workspace/memory/cron-schedule.json | grep -c '"id"' 2>/dev/null || echo "0")
  echo "[check] Cron schedule: $CRON_COUNT jobs"
else
  echo "[check] WARNING: cron-schedule.json not found!"
fi

# Bankr deploys
if [ -f "/data/bankr/bankr-config.json" ]; then
  DEPLOY_COUNT=$(cat /data/bankr/bankr-config.json | grep -c '"address"' 2>/dev/null || echo "0")
  echo "[check] Bankr deploys: $DEPLOY_COUNT tokens"
else
  echo "[check] WARNING: bankr-config.json not found!"
fi

# ATV config
if [ -f "/data/atv/atv-config.json" ]; then
  ATV_STATUS=$(cat /data/atv/atv-config.json | grep -o '"enabled": [a-z]*' | head -1)
  echo "[check] ATV identity: $ATV_STATUS"
else
  echo "[check] WARNING: atv-config.json not found!"
fi

# Hummingbot connection
if [ -n "$HUMMINGBOT_API_URL" ] && [ "$HUMMINGBOT_ENABLED" = "true" ]; then
  echo "[check] Hummingbot: ENABLED → $HUMMINGBOT_API_URL"
  # Wait for Hummingbot API to be ready (it starts in a separate container)
  echo "[check] Waiting for Hummingbot API to come online..."
  for i in $(seq 1 30); do
    if curl -s -o /dev/null -w "%{http_code}" "$HUMMINGBOT_API_URL/health" 2>/dev/null | grep -q "200"; then
      echo "[check] Hummingbot API: ONLINE ✓"
      break
    fi
    if [ $i -eq 30 ]; then
      echo "[check] Hummingbot API: NOT READY (will retry in background)"
    fi
    sleep 2
  done
else
  echo "[check] Hummingbot: DISABLED"
fi

# ========== ENV CHECK ==========
echo ""
echo "[check] ENV status:"
echo "  MINIMAX_API_KEY=$([ -n "$MINIMAX_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  OPENROUTER_API_KEY=$([ -n "$OPENROUTER_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  TELEGRAM_BOT_TOKEN=$([ -n "$TELEGRAM_BOT_TOKEN" ] && echo 'SET' || echo 'NOT SET')"
echo "  BANKR_API_KEY=$([ -n "$BANKR_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  BANKR_FEE_WALLET=$([ -n "$BANKR_FEE_WALLET" ] && echo 'SET' || echo 'NOT SET')"
echo "  ATV_API_URL=$([ -n "$ATV_API_URL" ] && echo 'SET' || echo 'NOT SET')"
echo "  ATV_ENABLED=$ATV_ENABLED"
echo "  HUMMINGBOT_API_URL=$([ -n "$HUMMINGBOT_API_URL" ] && echo 'SET' || echo 'NOT SET')"
echo "  HUMMINGBOT_ENABLED=$HUMMINGBOT_ENABLED"
echo "  GROK_API_KEY=$([ -n "$GROK_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  SERPER_API_KEY=$([ -n "$SERPER_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  HELIUS_API_KEY=$([ -n "$HELIUS_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  FIRECRAWL_API_KEY=$([ -n "$FIRECRAWL_API_KEY" ] && echo 'SET' || echo 'NOT SET')"
echo "  PERPLEXITY_ENABLED=$PERPLEXITY_ENABLED"
echo "  DEFAULT_MODEL=$DEFAULT_MODEL"

# ========== PERSISTENT STORAGE SUMMARY ==========
echo ""
echo "[check] Persistent storage layout:"
echo "  /data/bankr/           — Bankr config + deploy history"
echo "  /data/atv/             — ATV identity config + cache stats"
echo "  /data/hummingbot/      — HBot connection + trade history"
echo "  /data/pipeline/        — BD pipeline data"
echo "  /data/outreach/        — Outreach drafts + history"
echo "  /data/logs/            — Operation logs"
echo "  /data/workspace/memory — Cron schedules + agent memory"
echo "  /data/workspace/.env   — Env passthrough for cron jobs"

# ========== START GATEWAY ==========
echo ""
echo "=========================================="
echo "  Starting Buzz BD Agent v6.0.3"
echo "  Services: Buzz + Hummingbot API + MCP"
echo "              + EMQX Broker + PostgreSQL"
echo "  $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo "=========================================="
exec openclaw gateway --port 18789 --allow-unconfigured
