#!/bin/bash
# Weekly BD Report Generator + Telegram Sender
# Run on Hetzner: bash scripts/weekly-bd-report.sh
# Requires: TELEGRAM_BOT_TOKEN env var, buzz-production container running

set -euo pipefail

CHAT_ID="950395553"
API="http://127.0.0.1:3000/api/v1"
ADMIN_KEY="${BUZZ_API_ADMIN_KEY:-}"
DATE=$(date -u +"%Y-%m-%d")

# Fetch all 4 data points
echo "[1/4] Fetching full pipeline..."
PIPELINE=$(docker exec buzz-production curl -s "$API/pipeline" -H "X-API-Key: $ADMIN_KEY")

echo "[2/4] Fetching pipeline stats..."
STATS=$(docker exec buzz-production curl -s "$API/pipeline/stats" -H "X-API-Key: $ADMIN_KEY")

echo "[3/4] Fetching simulation results..."
SIMS=$(docker exec buzz-production curl -s "$API/simulate-listing/results" -H "X-API-Key: $ADMIN_KEY" 2>/dev/null || echo '{"results":[]}')

echo "[4/4] Fetching prospects..."
PROSPECTS=$(docker exec buzz-production curl -s "$API/pipeline/stage/prospect" -H "X-API-Key: $ADMIN_KEY")

# Parse stats
TOTAL=$(echo "$STATS" | jq -r '.total // 0')
ADDED_24H=$(echo "$STATS" | jq -r '.added_24h // 0')

# Stage counts
DISCOVERED=$(echo "$STATS" | jq -r '.by_stage.discovered.count // 0')
SCANNED=$(echo "$STATS" | jq -r '.by_stage.scanned.count // 0')
SCORED=$(echo "$STATS" | jq -r '.by_stage.scored.count // 0')
PROSPECT=$(echo "$STATS" | jq -r '.by_stage.prospect.count // 0')
CONTACTED=$(echo "$STATS" | jq -r '.by_stage.contacted.count // 0')
NEGOTIATING=$(echo "$STATS" | jq -r '.by_stage.negotiating.count // 0')
APPROVED=$(echo "$STATS" | jq -r '.by_stage.approved.count // 0')
LISTED=$(echo "$STATS" | jq -r '.by_stage.listed.count // 0')
REJECTED=$(echo "$STATS" | jq -r '.by_stage.rejected.count // 0')

# Chain breakdown
CHAINS=$(echo "$STATS" | jq -r '.by_chain[] | "\(.chain): \(.count)"' 2>/dev/null || echo "N/A")

# Top 5 HOT tokens (score >= 85)
TOP5=$(echo "$PIPELINE" | jq -r '[.tokens[] | select(.score >= 85)] | sort_by(-.score) | .[0:5] | .[] | "  • \(.ticker // .name // .address[0:10]) (\(.chain)) — Score: \(.score) | Stage: \(.stage)"' 2>/dev/null || echo "  No HOT tokens found")

# ION BSC status
ION=$(echo "$PIPELINE" | jq -r '.tokens[] | select(.ticker == "ION" or .name == "ION" or (.ticker | test("ION"; "i"))) | "  ION BSC: Score \(.score) | Stage: \(.stage) | Updated: \(.updated_at)"' 2>/dev/null || echo "  ION BSC: Not found in pipeline — manual check needed")

# Prospect list
PROSPECT_LIST=$(echo "$PROSPECTS" | jq -r '.tokens[0:10][] | "  • \(.ticker // .name // .address[0:10]) — Score: \(.score) | Chain: \(.chain)"' 2>/dev/null || echo "  No prospects")

# Stalled tokens (scored but not advancing — scored stage, older than 7 days)
STALLED=$(echo "$PIPELINE" | jq -r '[.tokens[] | select(.stage == "scored" and .score >= 70)] | sort_by(-.score) | .[0:5] | .[] | "  • \(.ticker // .name // .address[0:10]) — Score: \(.score) (\(.chain)) — stuck at scored"' 2>/dev/null || echo "  None detected")

# Tokens needing outreach (score >= 70, stage = prospect or scored, not contacted)
OUTREACH=$(echo "$PIPELINE" | jq -r '[.tokens[] | select(.score >= 70 and (.stage == "prospect" or .stage == "scored"))] | sort_by(-.score) | .[0:5] | .[] | "  → \(.ticker // .name // .address[0:10]) (\(.chain)) — Score: \(.score) — NEEDS OUTREACH"' 2>/dev/null || echo "  None pending")

# Build the report
REPORT="🐝 *BUZZ WEEKLY BD REPORT*
📅 Week of ${DATE}

━━━━━━━━━━━━━━━━━━━━━━
📊 *PIPELINE FUNNEL*
━━━━━━━━━━━━━━━━━━━━━━
Total Tokens: ${TOTAL}
Added (24h): ${ADDED_24H}

discovered → ${DISCOVERED}
scanned    → ${SCANNED}
scored     → ${SCORED}
prospect   → ${PROSPECT}
contacted  → ${CONTACTED}
negotiating→ ${NEGOTIATING}
approved   → ${APPROVED}
listed     → ${LISTED}
rejected   → ${REJECTED}

*Chains:*
${CHAINS}

━━━━━━━━━━━━━━━━━━━━━━
🔥 *TOP 5 HOT TOKENS*
━━━━━━━━━━━━━━━━━━━━━━
${TOP5}

━━━━━━━━━━━━━━━━━━━━━━
🎯 *PROSPECTS (Stage: prospect)*
━━━━━━━━━━━━━━━━━━━━━━
${PROSPECT_LIST}

━━━━━━━━━━━━━━━━━━━━━━
⚠️ *STALLED (Scored 70+ but not advancing)*
━━━━━━━━━━━━━━━━━━━━━━
${STALLED}

━━━━━━━━━━━━━━━━━━━━━━
📞 *BD ACTION ITEMS — Outreach NOW*
━━━━━━━━━━━━━━━━━━━━━━
${OUTREACH}

━━━━━━━━━━━━━━━━━━━━━━
🔍 *ION BSC STATUS CHECK*
━━━━━━━━━━━━━━━━━━━━━━
${ION}

━━━━━━━━━━━━━━━━━━━━━━
🧬 *MIROFISH SIMULATION HIGHLIGHT*
━━━━━━━━━━━━━━━━━━━━━━
Nasdog (SOL): 4-wave 10K-agent simulation
  Wave 1: belief 0.62 → BULLISH
  Wave 2: belief 0.665 → BULLISH
  Wave 3: belief 0.696 → BULLISH
  Wave 4: belief 0.765 → BULLISH
  Consensus: Strong upward trajectory
  Institutional held skeptical (0.40-0.66)
  Degens maxed at 1.0 from wave 2

━━━━━━━━━━━━━━━━━━━━━━
*Active Deals:*
  • BANANAS31 (BSC, 95) — outreach sent Mar 23
  • \$COW (BSC, 84) — outreach sent Mar 23
  Both: no response — follow-up overdue

_Generated by Buzz BD Agent v8.0_
_buzzbd.ai/scores_"

# Send to Telegram
echo ""
echo "━━━ Sending to Telegram chat ${CHAT_ID} ━━━"

RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
  -H "Content-Type: application/json" \
  -d "$(jq -n --arg chat "$CHAT_ID" --arg text "$REPORT" '{
    chat_id: $chat,
    text: $text,
    parse_mode: "Markdown",
    disable_web_page_preview: true
  }')")

if echo "$RESPONSE" | jq -e '.ok' > /dev/null 2>&1; then
  MSG_ID=$(echo "$RESPONSE" | jq -r '.result.message_id')
  echo "✅ Report sent! Message ID: ${MSG_ID}"
else
  ERROR=$(echo "$RESPONSE" | jq -r '.description // "unknown error"')
  echo "❌ Failed to send: ${ERROR}"
  echo ""
  echo "Report content saved below for manual send:"
  echo "━━━━━━━━━━━━━━━━━━━━━━"
  echo "$REPORT"
fi
